### ISSUE TITLE
Bug in music module

### ISSUE THREAD

**Issue by greatman** [greatman/legendarybot#27]
This song is making the bot crash: https://www.youtube.com/watch?v=eap0G9ldKc0

```
Feb 08 05:13:25 ERRORcom.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor: Error in playback of eap0G9ldKc0
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /yts/jsbin/player_remote_ux-vflZkVMZj/fr_FR/base.js
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:185)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:141)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getValidUrl(YoutubeSignatureCipherManager.java:100)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:99)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:60)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 common frames omitted

```

**Comment by greatman** [comment]
https://www.youtube.com/watch?v=MH9FyLsfDzw is another one

**Comment by greatman** [comment]
Fixed in latest version of lavaplayer: https://github.com/sedmelluq/lavaplayer/issues/85

**Comment by greatman** [comment]
Fixed in https://github.com/greatman/legendarybot/commit/367812dc225e249f9a0ad24a0b44936e60c415c2
